### PR TITLE
Optimizations for Gitbook Beta & Documentation Completion

### PR DESCRIPTION
**Pull request by ardacebi**
- Optimizations for Gitbook Beta.
- Other small changes such as typo fixes.

### CODE REVIEW

**Comment by barreeeiroo** [comment]
Mmm, there are a lot of files changed here
I'll take a look carefully next weekend 👍

**Comment by ardacebi** [comment]
Thank you @barreeeiroo,

I'll keep on making the changes until you check all.

**Comment by pavi2410** [comment]
@TurboProgramming Can you give us a link where we can see the changes live?

**Comment by ardacebi** [comment]
@pavi2410 https://makeroidturbofork.gitbook.io/project/

**Comment by ardacebi** [comment]
I've not been working on this for a long time, so you can merge for now. We'll see if I'll have time to work on this. I'm busy with something else.

**Comment by barreeeiroo** [comment]
Hey @TurboProgramming 
Can you fix all conflicts or start again with this? We changed lots of things since this

**Comment by ardacebi** [comment]
Just close the PR, I can't even open the web editor, it says that the conflicts are too complex to resolve in the web editor 😆

**Pull request closed without merging**
