### PR TITLE
Added Titles and Subtitles for remaining files + More useful edits

### PR DESCRIPTION
**Pull request by ardacebi**
Changes:
- Added Titles and Subtitles for remaining files.
- Added Icons to Pura Vida Extensions' (Extensions page/other category)
- Added Icons to MIT App Inventor/Thunkable etc. (Extensions Page/other category)
- Fixed some typos related to # usage for titles (text size)
- Release notes typo fixes.

## Ready to be merged with Makeroid:master.

### CODE REVIEW

**Comment by barreeeiroo** [comment]
@TurboProgramming Tomorrow I'm going to merge Peter's PullRequest as he has already filled all docs. If there's something missing I'll let you know, but Peter's PR has more priority than yours

**Comment by ardacebi** [comment]
@barreeeiroo OK, understood.

But remember that this PR also includes Typo fixes and some menu arrangements. So after you merge mine will it be a problem to merge Peter's?

**Comment by ardacebi** [comment]
PS: also some icons.

**Comment by ardacebi** [comment]
@barreeeiroo also, by this do you mean that I don't need to write the docs?

**Comment by PeterMathijssen** [comment]
@TurboProgramming I entered all the text from the original component documentation from App ínventor in the docs.

**Comment by ardacebi** [comment]
@PeterMathijssen But isn't Makeroid different than App Inventor? 

_(by that I mean the new properties, functions, blocks etc.)_

**Comment by PeterMathijssen** [comment]
@TurboProgramming Yes but most of the text of the original components can stay. Pieces can be altered for the differences of Makeroid.

**Comment by ardacebi** [comment]
Understood, so after @barreeeiroo merges your PR, can I add properties and blocks only available on Makeroid to those pages?

_(or are you going to?)_

**Comment by PeterMathijssen** [comment]
@TurboProgramming You can do that. That would be great.

**Comment by ardacebi** [comment]
Awesome 👍.

So now I'm waiting for @barreeeiroo to merge your PR. Then I will do that.

**Comment by barreeeiroo** [comment]
@TurboProgramming I'll merge tomorrow

**Comment by ardacebi** [comment]
I just want to ask something, isn't merging my PR before yours possible? Because I'm probably working on this for a few hours on this :)).

It looks like it's just 10 minutes but really it was hard.

**Comment by pavi2410** [comment]
If you wait till tomorrow, I will upload the generated documentation file from our source, so you only have to rearrange it.

**Comment by ardacebi** [comment]
OK. Thanks everyone.
@barreeeiroo 
@pavi2410 
@pavi2410 
@conorshipp

**Comment by pavi2410** [comment]
[component-doc.md.txt](https://github.com/Makeroid/docs/files/1622543/component-doc.md.txt)

This is the generated doc from our source in markdown format. It needs to formatted cleanly.

**Comment by ardacebi** [comment]
@pavi2410 what is that? I didn't understand.

**Comment by pavi2410** [comment]
That contains the documentation for all components.

**Comment by ardacebi** [comment]
So what can I do with it? format cleanly as you've said?

**Comment by barreeeiroo** [comment]
Some of your files were already merged with @PeterMathijssen PRs
Can you download your repo, fork again and then paste files without overwriting existing ones? So then we can just hit a button

**Comment by ardacebi** [comment]
I'm going to open another Pull Request. Closing this one.

**Pull request closed without merging**
