### PR TITLE
Title and Subtitle added for "UI", "Layout" and "Drawing and Animation"

### PR DESCRIPTION
**Pull request by ardacebi**
Editing Documentation

### CODE REVIEW

**Comment by Sander0542** [comment]
Why do you add /assets/touchcolor.png everywhere?

**Comment by ardacebi** [comment]
Copied title style from the Button documentation title. If you want I can change it to:

"# Component Name" instead of

"# Button"

**Comment by Sander0542** [comment]
8 files still contain the /assets/touchcolor.png

**Comment by ardacebi** [comment]
@Sander0542 I'm still editing them.

**Comment by ardacebi** [comment]
All of them are now done.

**Comment by ardacebi** [comment]
Remember that I only changed UI, Layout and Drawing and animation "For Now". In a few hours I will also add titles and subtitles for other components, elements too.

If I have extra time I will also write documentation for them.

**Comment by pavi2410** [comment]
No problem, we are in no hurry. Take your time

**Comment by Sander0542** [comment]
Just tell us when you want us to check your progress and tell us when you think its ready to be merged

**Comment by ardacebi** [comment]
Can you merge multiple times?

For example merge now, then a few hours later when I edit others, merge again?

**Comment by pavi2410** [comment]
If you want to see it live you fork our Gitbook

**Comment by Sander0542** [comment]
After I merge the PR is closed, but if I open it again, then I can merge again

**Comment by ardacebi** [comment]
OK, then don't merge it. After my work is done, I will inform you here.

**Comment by ardacebi** [comment]
Please merge this PR. I will contribute others by opening another PR. @Sander0542

**Comment by ardacebi** [comment]
After you merge the PR, will I gain this: https://community.makeroid.io/badges/111/makeroid-contributor?

**Comment by pavi2410** [comment]
Yes, of course

**Review by Sander0542 — APPROVED** [review]

**Comment by ardacebi** [comment]
Can't you merge this PR again (after I make changes)?

**Comment by Sander0542** [comment]
I think you need to create a new pull request

**Comment by ardacebi** [comment]
OK :) Thanks.

**Pull request merged**
