### PR TITLE
New docs to merge

### PR DESCRIPTION
**Pull request by PeterMathijssen**

### CODE REVIEW

**Comment by PeterMathijssen** [comment]
@PeterMathijssen Still learning i guess 😎

**Comment by Sander0542** [comment]
There are a lots of conflicts

**Comment by Sander0542** [comment]
my revert is not working

**Comment by Sander0542** [comment]
I created a new branch here with your latest commit as the latest one

check master2

**Comment by PeterMathijssen** [comment]
@Sander0542 I noticed also. According to Diego it could be fixed.

**Comment by Sander0542** [comment]
I have a branch with you latest commit as the latest, but I cant push it

**Comment by PeterMathijssen** [comment]
Did a new pull request. Now i get no error message.

**Review by barreeeiroo — APPROVED** [review]
Amazing! 😍

**Pull request merged**
