### PR TITLE
Big Documentation Update/PR

### PR DESCRIPTION
**Pull request by ardacebi**
Hello Developers,

I'm working on completing all Documentations right now. Created this Pull Request to notify you all and not editing anything. Merging PR's etc. 

This PR of mine is a big one and please merge it **only when I say here** because my work is still in progress. **Can you guys check how I'm going? (Check the Device Category > Audio & Screenshot those I've finished)**

By the way, all pages now have titles and no blank ones.

I've also renamed the "Lego" name "LEGO" as it's required to be written in all capital according to LEGO. And also renamed some edits made by @PeterMathijssen. By renames I mean I created spaces between for example ListView, I made it List View as it looks better.

Also some new text to the Introduction page, Useful Links, a brief summary of what is Makeroid, and a component list that helps people how to use the documentation (a getting started title).

### Don't merge this PR now, I'm going to inform you when my work is finished.

### CODE REVIEW

**Comment by ardacebi** [comment]
Can you merge this? I will complete the rest later.

**Comment by Sander0542** [comment]
We cant merge this. This will remove a lot of existing files. I would prefer if you could make more pull requests for changes instead of one with 100 edited files. Because if we change a few files, then we cant merge it anymore. So can you make new pull requests with only the files you want to change?

**Comment by ardacebi** [comment]
What do you mean by this? I've been working on writing documentation for hours!

Can't you do the rest? Merge this, then I can keep on adding the rest?

**Comment by Sander0542** [comment]
image

I cant merge it...

If I try to merge it, then the docs will be a mess. There will be docs deleted and moved

**Comment by ardacebi** [comment]
So what should I do?

If you could guide me what to do, I can help you.

**Comment by ardacebi** [comment]
by conflicting files what does it mean?

**Comment by Sander0542** [comment]
If you can copy all the files you edited to a new branch, then I can merge it (Make that new branch a copy of the current Makeroid/Docs)

**Comment by ardacebi** [comment]
When I try to create a new branch, it tries to create from my forked repository. How can I make it create from yours?

**Comment by Sander0542** [comment]
Try to edit a file in the Makeroid/Docs repo, then you should be able to create a new pull request with a new branch

**Comment by ardacebi** [comment]
OK, created the branch. So what do I need to do with it? Only add the files I changed by downloading the main branch as a .zip file?

**Comment by ardacebi** [comment]
Why Github gives an error like this? Have I done something wrong?

**Comment by Sander0542** [comment]
Yes, move only the files you want changed to the new branch

No. You didnt do anything wrong. There were many commits on the files your were changing

**Comment by ardacebi** [comment]
How can I understand which files I've changed? I've changed a lot of files.

Will it be hard doing it?

**Comment by Sander0542** [comment]
Look here what you changed and then move those files

https://github.com/Makeroid/docs/pull/14/files

**Comment by ardacebi** [comment]
Can I close this PR as I've opened another one?

**Pull request closed without merging**
