### PR TITLE
2nd Pull Request

### PR DESCRIPTION
**Pull request by ardacebi**
2nd Pull Request (See description of Big Documentation Update)

### CODE REVIEW

**Comment by ardacebi** [comment]
Please merge this @Sander0542

**Comment by ardacebi** [comment]
Before you merge this I want to ask something, why images on this page are not working?

https://github.com/TurboProgramming/docs/blob/patch-1/other/live-development.md

_(I've added a small guide on how to use the companion.)_

**Comment by Sander0542** [comment]
Did you look which files you are going to merge?! You are again removing new stuff

**Comment by ardacebi** [comment]
I haven't removed anything this time, I've uploaded the folders from the other branch.

**Comment by ardacebi** [comment]
This time it looks like there are no any errors. 

The reason I've removed those files (on the other branch) because they are not necessary, just blank files. 

Mostly I have categorized the files (For example a new Google folder for the new google category).

**Comment by Sander0542** [comment]
network.md
image-sprite.md
media.md
sensors.md
finger-print.md

**Comment by ardacebi** [comment]
@Sander0542 ...yes?

**Comment by ardacebi** [comment]
Those files are still at there location.

**Comment by Sander0542** [comment]
You need to change those files

**Comment by ardacebi** [comment]
I've changed the location of the FingerPrint component to Sensors from Experimental (As seen in Makeroid Builder)

Others have small changes such as sensors.md, I've added Fingerprint to the list.

Should I copy and reupload the stock file from the main repository? (makeroid/docs)

**Comment by Sander0542** [comment]
Let me make some commits to your branch

**Comment by ardacebi** [comment]
Of course!
But, do I need to give permission somewhere? ..or can you make changes directly?

**Comment by Sander0542** [comment]
I think that I don't need any permission 😉 

image

**Comment by ardacebi** [comment]
When you're done you can merge the PR.

**Comment by TurboProgramming** [comment]
Why is the Google category not visible?

**Comment by TurboProgramming** [comment]
I've created it.

**Comment by Sander0542** [comment]
You didn't. I have created it now

**Pull request merged**
